---
development:
  cloud_name: df8jfhyew
  api_key: '812251998617867'
  api_secret: fwsm2UH1muCdpQryByd4ee3fBLk
  enhance_image_tag: true
  static_file_support: false
production:
  cloud_name: df8jfhyew
  api_key: '812251998617867'
  api_secret: fwsm2UH1muCdpQryByd4ee3fBLk
  enhance_image_tag: true
  static_file_support: true
test:
  cloud_name: df8jfhyew
  api_key: '812251998617867'
  api_secret: fwsm2UH1muCdpQryByd4ee3fBLk
  enhance_image_tag: true
  static_file_support: false
